import logging

LOG_FILE = "system.log"
LOG_LEVEL = logging.DEBUG
HEALTH_INTERVAL = 5

TEMP_THRESHOLD = 60
PRESSURE_THRESHOLD = 30
VIBRATION_THRESHOLD = 5.0
FUEL_FLOW_THRESHOLD = 10
VOLTAGE_THRESHOLD = 210
SPEED_THRESHOLD = 120
BRAKE_PRESSURE_THRESHOLD = 40
HUMIDITY_THRESHOLD = 80
ENGINE_LOAD_THRESHOLD = 90